### PR TITLE
fix: localization for "Click to close"

### PR DESCRIPTION
**Pull request by anthonyronda**
Ref #31

### CODE REVIEW

**Comment by anthonyronda** [comment]
@MS-PBS is this good or should it be something else?
https://github.com/vttred/tips/pull/32/commits/604b01a52f494fef3ee89365ad52de50615f8d6a#diff-b1642b24a7632e66b79b655dd84510e978c26e2043509bbb3f6e717848ffee59

**Comment by MS-PBS** [comment]
> 
> 
> @MS-PBS is this good or should it be something else?
> [604b01a#diff-b1642b24a7632e66b79b655dd84510e978c26e2043509bbb3f6e717848ffee59](https://github.com/vttred/tips/commit/604b01a52f494fef3ee89365ad52de50615f8d6a#diff-b1642b24a7632e66b79b655dd84510e978c26e2043509bbb3f6e717848ffee59)

It is formal Spanish. It is not incorrect, however I would change it to "Haz click para cerrar".

**Comment by anthonyronda** [comment]
@MS-PBS Thanks so much for your contributions to this module, you have no idea what it means to me to have your translations in here!

I've implemented this change

Note that I added a menu option to the module yesterday. If you plan to translate more but you prefer to wait until there's more to translate, there will be several more features and new tips Sunday and Monday

**Comment by MS-PBS** [comment]
> 
> 
> @MS-PBS Thanks so much for your contributions to this module, you have no idea what it means to me to have your translations in here!
> 
> I've implemented this change
> 
> Note that I added a menu option to the module yesterday. If you plan to translate more but you prefer to wait until there's more to translate, there will be several more features and new tips Sunday and Monday

No problem man. If you want to add more lines to es.json it would really help me if you can preface any untranslated lines with [EN] or something similar, to make it easier for me to find them. Although in the case of this module, since all lines are numbered (and I assume you'll append new tips at the end), this should be less of an issue than with other modules. I will check from time to time to see if there's anything new to translate. If it's been a while and you have a lot of new tips in need of translation, feel free to @ me.

**Comment by anthonyronda** [comment]
I'll definitely find ways to tag future changes in a more visible way

**Pull request merged**
